# Generated by Django 3.2.25 on 2024-10-10 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('capacity', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('workshop', 'Workshop'), ('conference', 'Conference'), ('webinar', 'Webinar'), ('meetup', 'Meetup'), ('networking', 'Networking'), ('seminar', 'Seminar'), ('concert', 'Concert'), ('festival', 'Festival'), ('sports', 'Sports Event'), ('fundraiser', 'Fundraiser'), ('exhibition', 'Exhibition'), ('class', 'Class'), ('party', 'Party')], default='eventtype', max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('free', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
