# Generated by Django 3.2.25 on 2024-10-08 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('conference', 'Conference'), ('webinar', 'Webinar'), ('meetup', 'Meetup'), ('networking', 'Networking'), ('seminar', 'Seminar'), ('concert', 'Concert'), ('festival', 'Festival'), ('sports', 'Sports Event'), ('fundraiser', 'Fundraiser'), ('exhibition', 'Exhibition'), ('class', 'Class'), ('party', 'Party')], default='eventtype', max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event'),
        ),
    ]
