# Generated by Django 3.2.25 on 2024-11-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
