# Generated by Django 3.2.25 on 2024-11-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('conference', 'Conference'), ('webinar', 'Webinar'), ('meetup', 'Meetup'), ('networking', 'Networking'), ('seminar', 'Seminar'), ('concert', 'Concert'), ('festival', 'Festival'), ('sports', 'Sports Event'), ('fundraiser', 'Fundraiser'), ('exhibition', 'Exhibition'), ('class', 'Class'), ('party', 'Party')], default='workshop', max_length=100),
        ),
    ]
