# Generated by Django 3.2.25 on 2024-11-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
