# Generated by Django 5.1.3 on 2024-11-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.URLField(default='https://example.com/default-image.jpg', max_length=500),
        ),
    ]
