# Generated by Django 3.2.25 on 2024-11-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
